/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SportsSportRouteImport } from './routes/sports.$sport'
import { Route as SportsSportIndexRouteImport } from './routes/sports.$sport.index'
import { Route as SportsSportLeagueRouteImport } from './routes/sports.$sport.$league'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsSportRoute = SportsSportRouteImport.update({
  id: '/sports/$sport',
  path: '/sports/$sport',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsSportIndexRoute = SportsSportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SportsSportRoute,
} as any)
const SportsSportLeagueRoute = SportsSportLeagueRouteImport.update({
  id: '/$league',
  path: '/$league',
  getParentRoute: () => SportsSportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sports/$sport': typeof SportsSportRouteWithChildren
  '/sports/$sport/$league': typeof SportsSportLeagueRoute
  '/sports/$sport/': typeof SportsSportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sports/$sport/$league': typeof SportsSportLeagueRoute
  '/sports/$sport': typeof SportsSportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sports/$sport': typeof SportsSportRouteWithChildren
  '/sports/$sport/$league': typeof SportsSportLeagueRoute
  '/sports/$sport/': typeof SportsSportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/sports/$sport'
    | '/sports/$sport/$league'
    | '/sports/$sport/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/sign-in' | '/sign-up' | '/sports/$sport/$league' | '/sports/$sport'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/sports/$sport'
    | '/sports/$sport/$league'
    | '/sports/$sport/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SportsSportRoute: typeof SportsSportRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/$sport': {
      id: '/sports/$sport'
      path: '/sports/$sport'
      fullPath: '/sports/$sport'
      preLoaderRoute: typeof SportsSportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/$sport/': {
      id: '/sports/$sport/'
      path: '/'
      fullPath: '/sports/$sport/'
      preLoaderRoute: typeof SportsSportIndexRouteImport
      parentRoute: typeof SportsSportRoute
    }
    '/sports/$sport/$league': {
      id: '/sports/$sport/$league'
      path: '/$league'
      fullPath: '/sports/$sport/$league'
      preLoaderRoute: typeof SportsSportLeagueRouteImport
      parentRoute: typeof SportsSportRoute
    }
  }
}

interface SportsSportRouteChildren {
  SportsSportLeagueRoute: typeof SportsSportLeagueRoute
  SportsSportIndexRoute: typeof SportsSportIndexRoute
}

const SportsSportRouteChildren: SportsSportRouteChildren = {
  SportsSportLeagueRoute: SportsSportLeagueRoute,
  SportsSportIndexRoute: SportsSportIndexRoute,
}

const SportsSportRouteWithChildren = SportsSportRoute._addFileChildren(
  SportsSportRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SportsSportRoute: SportsSportRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
